import Head from 'next/head';
import Image from 'next/image';
import Nav from './layout/nav';
import Link from 'next/link';
import { FaRegClock } from "react-icons/fa";
import {FaUser} from "react-icons/fa";
import HomeService from '../service/home.service';
import  CategoryService from "../service/category.service";
import { useGetFromStore } from '../hook/customHook';
import { increment } from '../redux/reducers/example';
import { useDispatch } from 'react-redux';
import { getCount } from '../redux/reducers/selector';
export default function Home({data, nav}) {
//     const dispatch = useDispatch();
//    const dataCC = useGetFromStore(getCount);
//    if(dataCC){
//       console.log(dataCC);
//    }
 const dataRowFirst = data.rowFirst;
 const dataRowSecond = data.rowSecond;
 const dataRowSeconds = data.length !== 0 ? data.rowSecond.Post_categories : [];
 const dataRowThird = data.rowThird;
 const dataRandomFirst = data.randomFirst;
 const dataRandomSecond = data.randomSecond;
 const dataRowFour = data.rowFour;
 const dataRowFive = data.rowFive;
 const dataRandom = data.rowRandom;
  return (
    <div>
      <Head>
        <title>Page home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="app-block-top container-fluid">

        



           <div className="container">
              <div className="app-block-top_grid">

              
              {dataRowFirst && dataRowFirst.map((item, key) => (
                <div key={key} className="app-block-top_grid-item">
                <div className="app-block-top_grid-item-image">
                    <img src={ item.Post_categories[0].Post.thumb} alt="" />
                    <div className="app-block-top_grid-item-image-tag">
                        {item.title}
                    </div>
                    <div className="app-block-top_grid-item-image-gradient"></div>
                    <div className="app-block-top_grid-item-image-tag-content">
                        <div className="app-block-top_grid-item-image-tag-content-title ">
                            <Link href={"/post/" + item.Post_categories[0].Post.slug}><span className="tag__font-big">{item.Post_categories[0].Post.title}</span></Link>
                        </div>
                        <div className="app-block-center__third-content-item-detail-author">
                            <span><FaUser /> {item.Post_categories[0].Post.User.name}</span>
                            <span><FaRegClock /> {(item.Post_categories[0].Post.createdAt).slice(0, 10)}</span>
                        </div>
                    </div>
                </div>
            </div>
              ))}
             

               
              </div>
           </div>
      </section> 
       <section className="app-block-center container-fluid">
         <div className="container">
            <div className="app-block-center_content">
                <div className="app-block-center_content-post ">
                   <div className="app-block-center_content-post-flex">
                       <div className="app-tab__title tab-red">
                           <div className="app-tab__title-left">
                              <Link href=""><span>{dataRowSecond  && dataRowSecond.title}</span></Link>
                           </div>
                           <div className="app-tab__title-right">
                              <Link href=""><span>Xem thêm</span></Link>
                        </div>
                       </div>
                   

                   
                       <div className="row">
                          <div className="col-sm-6 ">
                            <div className="app-block-center_content-post-flex-item ">
                                <div className="app-block-center_content-post-flex-item-image">
                                    <img src={ dataRowSecond.Post_categories[0].Post.thumb} alt="" />

                                   
                                    <div className="app-block-top_grid-item-image-gradient"></div>
                                    <div className="app-block-top_grid-item-image-tag-content">
                                        <div className="app-block-top_grid-item-image-tag-content-title ">
                                            <Link href={"/post/" + dataRowSecond.Post_categories[0].Post.slug}><span className="tag__font-big">{dataRowSecond.Post_categories[0].Post.title}</span></Link>
                                        </div>
                                        <div className="app-block-center__third-content-item-detail-author">
                                            <span><FaUser /> Vũ Minh Hùng</span>
                                            <span> <FaRegClock /> {(dataRowSecond.Post_categories[0].Post.createdAt).slice(0, 10)}</span>
                                        </div>
                                    </div>





                                </div>
                            </div>
                          </div>
                          <div className="col-sm-6 ">
                            <div className="app-block-center_content-post-flex-item ">
                                <div className="app-block-center_content-post-flex-item-news">

                                {dataRowSeconds && dataRowSeconds.map((item, key) => {
                                    if(key === 0){
                                        return('');
                                    }else {
                                        return( <div key={key} className="app-block-center_content-post-flex-news-item">
                                        <div className="app-block-center_content-post-flex-news-item-image">
                                            <img src={ item.Post.thumb} alt="" />
                                        </div>
                                        <div className="app-block-center_content-post-flex-news-item-content">
                                             <div className="app-block-center_content-post-flex-news-item-title">
                                                <Link href={"/post/" + item.Post.slug}><span>{item.Post.title}</span></Link>
                                             </div>
                                             <div className="app-block-center_content-post-flex-news-item-detail">
                                                <Link href={"/post/" + item.Post.slug}> <FaRegClock /> <span>{(item.Post.createdAt).slice(0, 10)}</span></Link>
                                             </div>
                                        </div>
                                    </div>)
                                    }
                                  
                                })}
                                   
                                   
                                   
                                </div>
                            </div>
                          </div>
                       </div>
                   
                   </div>

                   <div className="app-block-center__second-content">
                    <div className="app-tab__title tab-blue">
                        <div className="app-tab__title-left">
                           <Link href=""><span>Bài viết gợi ý</span></Link>
                        </div>
                        <div className="app-tab__title-right">
                           <Link href=""><span>Xem thêm</span></Link>
                     </div>
                    </div>
                    <div className="app-block-center__second-content-tab">

                 
                          <div className="row">
                          
                          {dataRandomFirst && dataRandomFirst.map((item, key) => (
                             <div key={key} className="col-sm-4">
                             <div className="app-block-center__second-content-item">
                                 <div className="app-block-center__second-content-item-image">
                                    <img src={ item.thumb} alt="" />
                                 </div>
                                 <div className="app-block-center__second-content-item-content">
                                    <Link href={"/post/" + item.slug}> <span>{item.title}</span></Link>
                                    <Link href={"/post/" + item.slug}><FaRegClock />  <span className="author">{item.createdAt.slice(0, 10)}</span></Link>
                                 </div>
                             </div>
                         </div>
                          ))}
                         
                            
                          </div>
                        </div>
                   </div>

                   <div className="app-block-center__third-content">
                    <div className="app-tab__title tab-orange">
                        <div className="app-tab__title-left">
                           <Link href=""><span>{dataRowThird && dataRowThird.title}</span></Link>
                        </div>
                        <div className="app-tab__title-right">
                           <Link href=""><span>Xem thêm</span></Link>
                     </div>
                    </div>
                    
                    {dataRowThird.Post_categories && dataRowThird.Post_categories.map((item, key) => (
                         <div key={key} className="app-block-center__third-content-item">
                         <div className="app-block-center__third-content-item-image">
                             <img src={ item.Post.thumb} alt="" />
                         </div>
                         <div className="app-block-center__third-content-item-detail">
                             <div className="app-block-center__third-content-item-detail-title">
                                 <Link href={"/post/" + item.Post.slug}><span>{item.Post.title}</span></Link>
                             </div>
                             <div className="app-block-center__third-content-item-detail-author">
                                 <span><FaUser /> {item.Post.User.name}</span>
                                 <span><FaRegClock />  {item.Post.createdAt.slice(0, 10)}</span>
                             </div>
                             <div className="app-block-center__third-content-item-detail-thumbnail">
                                 <Link href={"/post/" + item.Post.slug}><span>{item.Post.description}</span></Link>
                             </div>
                         </div>
                       </div>
                    ))}
                  


                      <div className="app-block-center__third-content-show-more">
                          <Link href="/post/search?key="><button>Xem thêm</button></Link> 
                      </div>
                   </div>

                   <div className="app-block-center__second-content">
                    <div className="app-tab__title green-tab">
                        <div className="app-tab__title-left">
                           <Link href=""><span>Bài viết trước đây</span></Link>
                        </div>
                        <div className="app-tab__title-right">
                           <Link href=""><span>Xem thêm</span></Link>
                     </div>
                    </div>
                    <div className="app-block-center__second-content-tab">             
                    <div className="row">
                  
                    {dataRandomSecond && dataRandomSecond.map((item, key) => (
                          <div key={key} className="col-sm-4">
                          <div className="app-block-center__second-content-item">
                              <div className="app-block-center__second-content-item-image">
                                 <img src={ item.thumb} alt="" />
                              </div>
                              <div className="app-block-center__second-content-item-content">
                                 <Link href={"/post/" + item.slug}> <span>{item.title}</span></Link>
                                 <Link href={"/post/" + item.slug}><FaRegClock /> <span className="author">{item.createdAt.slice(0, 10)}</span></Link>
                              </div>
                          </div>
                      </div>
                    ))}
                   
                      
                     
                    </div>
                </div>
                   </div>

                   <div className="app-block-center__last-content">
                    
                         <div className="row">
                            <div className="col-sm-6">
                                
                                <div className="app-block-center__last-content-item">
                                    <div className="app-tab__title yellow-tab">
                                        <div className="app-tab__title-left">
                                           <Link href=""><span>{dataRowFour.title}</span></Link>
                                        </div>
                                        <div className="app-tab__title-right">
                                           <Link href=""><span>Xem thêm</span></Link>
                                     </div>
                                    </div>
                                    <div className="app-block-center__last-content-item-top">
                                        <img src={ dataRowFour.Post_categories[0].Post.thumb} alt="" />
                                        <div className="app-block-top_grid-item-image-gradient"></div>
                                        <div className="app-block-top_grid-item-image-tag-content">
                                            <div className="app-block-top_grid-item-image-tag-content-title "><Link href={"/post/" + dataRowFour.Post_categories[0].Post.slug}>
                                                <span className="tag__font-big">{dataRowFour.Post_categories[0].Post.title}</span></Link>
                                                </div>
                                                <div className="app-block-center__third-content-item-detail-author"><span><FaUser /> Vũ Minh Hùng</span><span> <FaRegClock /> {dataRowFour.Post_categories[0].Post.createdAt.slice(0, 10)}</span>
                                                </div>
                                                </div>
                                    </div>
                                    <div className="app-block-center__last-content-item-list">
                                    {dataRowFour.Post_categories && dataRowFour.Post_categories.map((item, key) => {
                                        if(key === 0){
                                            return ('');
                                        }else {
                                            return(  <div key={key} className="app-block-center__last-content-item-list-flex">
                                            <div className="app-block-center__last-content-item-list-flex-image">
                                                <img src={ item.Post.thumb} alt="" />
                                            </div>
                                            <div className="app-block-center__last-content-item-list-flex-detail">
                                                <Link href={"/post/" + item.Post.slug}><span>{item.Post.title}
                                                </span></Link>
                                                <span className="author"><FaRegClock /> {item.Post.createdAt.slice(0, 10)}</span>
                                            </div>
                                        </div>);
                                        }
                                    })}
                                      
                                       
                                    </div>
                                </div>
                             </div>
                             <div className="col-sm-6">
                                <div className="app-block-center__last-content-item">
                                    <div className="app-tab__title darkmagenta-tab">
                                        <div className="app-tab__title-left">
                                           <Link href=""><span>{dataRowFive.title}</span></Link>
                                        </div>
                                        <div className="app-tab__title-right">
                                           <Link href=""><span>Xem thêm</span></Link>
                                     </div>
                                    </div>
                                    <div className="app-block-center__last-content-item-top">
                                        <img src={ dataRowFive.Post_categories[0].Post.thumb} alt="" />
                                        <div className="app-block-top_grid-item-image-gradient"></div>
                                        <div className="app-block-top_grid-item-image-tag-content">
                                            <div className="app-block-top_grid-item-image-tag-content-title "><Link href={"/post/" + dataRowFive.Post_categories[0].Post.slug}>
                                                <span className="tag__font-big">{dataRowFive.Post_categories[0].Post.title}</span></Link>
                                                </div>
                                                <div className="app-block-center__third-content-item-detail-author"><span><FaUser /> Vũ Minh Hùng</span><span> <FaRegClock />{dataRowFive.Post_categories[0].Post.createdAt.slice(0, 10)}</span>
                                                </div>
                                                </div>
                                    </div>
                                    <div className="app-block-center__last-content-item-list">
                                    {dataRowFive.Post_categories && dataRowFive.Post_categories.map((item, key) => {
                                        if(key === 0){
                                            return ('');
                                        }else {
                                            return(  <div key={key} className="app-block-center__last-content-item-list-flex">
                                            <div className="app-block-center__last-content-item-list-flex-image">
                                                <img src={ item.Post.thumb} alt="" />
                                            </div>
                                            <div className="app-block-center__last-content-item-list-flex-detail">
                                                <Link href={"/post/" + item.Post.slug}><span>{item.Post.title}
                                                </span></Link>
                                                <span className="author"><FaRegClock /> {item.Post.createdAt.slice(0, 10)}</span>
                                            </div>
                                        </div>);
                                        }
                                    })}
                                      
                                       
                                    </div>
                                </div>
                             </div>
                         </div>
                   </div>
                    
                   <div className="app-block-center__grid-content-box">
                   <div className="app-tab__title green-tab">
                    <div className="app-tab__title-left">
                       <Link href=""><span>Bài viết gợi ý</span></Link>
                    </div>
                    <div className="app-tab__title-right">
                       <Link href=""><span>Show more</span></Link>
                 </div>
                   </div>
                   <div className="app-block-center__grid-content">
                   {dataRandom && dataRandom.map((item, key) => (
                      <div key={key} className="app-block-center__grid-content-item">
                      <div className="app-block-center__grid-content-item-image">
                          <img src={ item.thumb} alt="" />
                      </div>
                      <div className="app-block-center__grid-content-item-content">
                           <Link href={"/post/" + item.slug}> <span>{item.title}
                          </span></Link>
                          <span className="author"><FaRegClock />  {item.createdAt.slice(0, 10)}</span>
                      </div>
                  </div>
                   ))}
                    </div>
                </div>
                </div>
              
            <Nav data={nav}/>

             </div>
         </div>
      </section>  
    </div>
  )
}
export async function getServerSideProps() {
    const data = await HomeService.getHome();
    const nav = await HomeService.getNav();
    const header = await CategoryService.index();
    return { props: { data, nav, header } };
  }